title: gbmcarlos
email: gbmcarlos@gmail.com
description: >-
  Carlos Garcia-Berro Molero
twitter_username: gbmcarlos
github_username: gbmcarlos

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
